#include<iostream>

using namespace std;

int main()
{

/*

int a = 123;

cout<<a<<endl;


char b = 'x';

cout<<b<<endl;

float f = 1.2;

cout<<f<<endl;

double d = 1.2222;

cout<<d<<endl;


int size = sizeof(d);

cout<<"the size of "<<size<<" is "<<endl;



int a = 'a';

cout<<a<<endl;


char ch = 97;

cout<<ch<<endl;


char ch1 = 123456;
cout<<ch1<<endl;
*/


unsigned int a = -112;

cout<<a<<endl;


int x = 2 , y = 3 ;

bool f = (x==y);

cout<<f<<endl;


bool s = (x>y);
cout<<s<<endl;

bool t = (x<y);

cout<<t<<endl;


bool r = (x<=y);

cout<<r<<endl;


}